server:
  port: 8081

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/night?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: 123456789
      deriver_class: com.mysql.cj.jdbc.Driver

  mybatis:
      mapper-localtions: classpath:/mapper/*.xml

person: 
  name: zhangsan
  age: 18
  boss: false
  brith: 2020/08/01
  maps: {k1: v1,k2: v2}
  lists:
    - list1
    - list2
  dog:
    name: 小狗
    age: 2
